// utils/bossConfig.js
export const DEV_SETTINGS = {
  FORCE_BOSS_ID: null,
  EVERY_ROUND_IS_BOSS: false,
};

export const MINI_BOSS_REGISTRY = {
  "two-word": {
    id: "two-word",
    category: "multi",
    wordCount: 2,
    maxTurns: 7,
  },
};
export const MINI_BOSS_TYPES = Object.values(MINI_BOSS_REGISTRY);

export const BOSS_REGISTRY = {
  wordle500: {
    id: "wordle500",
    category: "special",
    wordCount: 1,
    maxTurns: 8,
  },
  "four-word": {
    id: "four-word",
    category: "multi",
    wordCount: 4,
    maxTurns: 10,
  },
  "shape-boss": {
    id: "shape-boss",
    category: "shape",
    wordCount: 1,
    maxTurns: 6,
  },
};

export const BOSS_TYPES = Object.values(BOSS_REGISTRY);

export const SOLUTION_WORD_COUNT = 2315;
export const HARD_SOLUTION_WORD_COUNT = 798;

export const SHAPE_KEYS = [
  "shape-t",
  "shape-u",
  "shape-x",
  "shape-diamond",
  "shape-hourglass",
  "shape-arrow",
  "shape-heart",
  "shape-finger",
  "shape-smile",
  "shape-alien",
  "shape-sword",
  "shape-tree",
  "shape-cup",
  "shape-snake",
  "shape-check",
  "shape-star",
  "shape-boat",
  "shape-robot",
  "shape-key",
  "shape-lightning",
  "shape-mushroom",
  "shape-crown",
  "shape-bell",
  "shape-flag",
  "shape-anchor",
  "shape-spider",
  "shape-ghost",
  "shape-moon",
  "shape-shield",
  "shape-spade",
  "shape-fish",
  "shape-tulip",
  "shape-butterfly",
  "shape-camera",
  "shape-bone",
  "shape-rocket",
  "shape-lock",
  "shape-cherry",
  "shape-umbrella",
  "shape-anvil",
  "shape-flask",
  "shape-axe",
  "shape-cactus",
  "shape-car",
  "shape-guitar",
];

export const SHAPES = {
  "shape-t": [
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "G", "x", "x"],
  ],
  "shape-u": [
    ["G", "x", "x", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["Y", "x", "G", "x", "Y"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "G", "x", "G", "G"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-x": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-diamond": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-hourglass": [
    ["G", "G", "G", "G", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
  ],
  "shape-arrow": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-heart": [
    ["x", "G", "x", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-finger": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-smile": [
    ["x", "G", "x", "G", "x"],
    ["x", "x", "x", "x", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-alien": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["Y", "x", "Y", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-sword": [
    ["Y", "x", "G", "x", "Y"],
    ["x", "Y", "G", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-tree": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "Y", "Y", "x"],
  ],
  "shape-cup": [
    ["G", "x", "G", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-snake": [
    ["G", "G", "x", "x", "x"],
    ["x", "G", "G", "x", "x"],
    ["x", "x", "G", "G", "x"],
    ["x", "x", "x", "Y", "Y"],
    ["x", "x", "Y", "Y", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-check": [
    ["x", "x", "x", "x", "G"],
    ["x", "x", "x", "G", "x"],
    ["G", "x", "G", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "Y", "x", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-star": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
  ],
  "shape-boat": [
    ["x", "x", "x", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-robot": [
    ["x", "G", "G", "G", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "G", "x", "G"],
    ["Y", "G", "x", "G", "Y"],
    ["x", "Y", "G", "Y", "x"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-key": [
    ["x", "G", "G", "G", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
  ],
  "shape-lightning": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "x", "x"],
    ["G", "Y", "G", "x", "x"],
    ["x", "x", "Y", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-mushroom": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-crown": [
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["Y", "x", "G", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-bell": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-flag": [
    ["x", "G", "G", "G", "x"],
    ["x", "G", "x", "Y", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "Y", "x", "x", "x"],
    ["x", "Y", "x", "x", "x"],
    ["x", "G", "x", "x", "x"],
  ],
  "shape-anchor": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-spider": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "Y", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-ghost": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-moon": [
    ["x", "x", "G", "G", "x"],
    ["x", "G", "Y", "x", "x"],
    ["G", "x", "x", "x", "x"],
    ["G", "x", "Y", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "x", "G", "G", "x"],
  ],
  "shape-shield": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "Y", "G", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-spade": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-fish": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "Y"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-tulip": [
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-butterfly": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-camera": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "x", "x", "x"],
  ],
  "shape-bone": [
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
  ],
  "shape-rocket": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-lock": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-cherry": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "x", "Y", "x"],
    ["G", "x", "x", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-umbrella": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "x", "x"],
  ],
  "shape-anvil": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
  ],
  "shape-flask": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-axe": [
    ["x", "G", "G", "x", "x"],
    ["G", "Y", "G", "x", "x"],
    ["x", "G", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-cactus": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "G"],
    ["G", "x", "G", "Y", "G"],
    ["G", "Y", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "G", "Y", "x"],
  ],
  "shape-car": [
    ["x", "x", "x", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "G", "G", "G", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "Y", "x", "Y", "x"],
  ],
  "shape-guitar": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
  ],
};
