// utils/bossConfig.js

export const DEV_SETTINGS = {
  FORCE_BOSS_ID: "shape-boss",
  EVERY_ROUND_IS_BOSS: true,
};

export const BOSS_REGISTRY = {
  wordle500: {
    id: "wordle500",
    category: "special",
    wordCount: 1,
    maxTurns: 8,
  },
  "two-word": { id: "two-word", category: "multi", wordCount: 2, maxTurns: 7 },
  "four-word": {
    id: "four-word",
    category: "multi",
    wordCount: 4,
    maxTurns: 10,
  },
  "shape-boss": {
    id: "shape-boss",
    category: "shape",
    wordCount: 1,
    maxTurns: 6,
  },
};

export const BOSS_TYPES = Object.values(BOSS_REGISTRY);
export const SOLUTION_WORD_COUNT = 2315;

export const SHAPE_KEYS = [
  "shape-t",
  "shape-u",
  "shape-x",
  "shape-square",
  "shape-diamond",
  "shape-hourglass",
  "shape-plus",
  "shape-zigzag",
  "shape-arrow",
  "shape-heart",
  "shape-finger",
  "shape-ladder",
  "shape-smile",
  "shape-alien",
  "shape-sword",
  "shape-tree",
  "shape-cup",
  "shape-house",
  "shape-snake",
  "shape-check",
];

export const SHAPES = {
  "shape-t": [
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "G", "x", "x"],
  ],
  "shape-u": [
    ["G", "x", "x", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "G", "x", "G", "G"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-x": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-square": [
    ["G", "G", "G", "G", "G"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "x", "x", "x", "G"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-diamond": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-hourglass": [
    ["G", "G", "G", "G", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
  ],
  "shape-plus": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-zigzag": [
    ["G", "x", "x", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "x", "Y", "x"],
    ["x", "x", "x", "x", "Y"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-arrow": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-heart": [
    ["x", "G", "x", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-finger": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-ladder": [
    ["G", "x", "x", "x", "G"],
    ["G", "G", "G", "G", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-smile": [
    ["x", "G", "x", "G", "x"],
    ["x", "x", "x", "x", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-alien": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["Y", "x", "Y", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-sword": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-tree": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "Y", "Y", "x"],
  ],
  "shape-cup": [
    ["G", "x", "G", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-house": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-snake": [
    ["G", "G", "x", "x", "x"],
    ["x", "G", "G", "x", "x"],
    ["x", "x", "G", "G", "x"],
    ["x", "x", "x", "Y", "Y"],
    ["x", "x", "Y", "Y", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-check": [
    ["x", "x", "x", "x", "G"],
    ["x", "x", "x", "G", "x"],
    ["G", "x", "G", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "Y", "x", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
};
