// utils/bossConfig.js
export const DEV_SETTINGS = {
  FORCE_BOSS_ID: "bomb-boss",
  EVERY_ROUND_IS_BOSS: true,
};

export const MINI_BOSS_REGISTRY = {
  "two-word": {
    id: "two-word",
    category: "multi",
    wordCount: 2,
    maxTurns: 7,
  },
  "bomb-boss": {
    id: "bomb-boss",
    category: "bomb",
    wordCount: 1, // Standard single-word entry per row
    maxTurns: 6,
  },
};
export const MINI_BOSS_TYPES = Object.values(MINI_BOSS_REGISTRY);

export const BOMB_PHRASES = {
    "easy": [
        "ch",
        "sh",
        "th",
        "wh",
        "ph",
        "gh",
        "ck",
        "ng",
        "ll",
        "ss",
        "ff",
        "rr",
        "tt",
        "ee",
        "oo",
        "ea",
        "oa",
        "ou",
        "ie",
        "ei",
        "ai",
        "ay",
        "er",
        "ar",
        "or",
        "ur",
        "ir",
        "re",
        "le",
        "st",
        "sp",
        "sk",
        "sc",
        "sm",
        "sn",
        "sl",
        "sw",
        "pr",
        "tr",
        "cr",
        "br",
        "gr",
        "fr",
        "pl",
        "cl",
        "bl",
        "gl",
        "fl",
        "nt",
        "nd",
        "rt",
        "lt",
        "mp",
        "nk",
        "nc",
        "ma",
        "pa",
        "te",
        "co",
        "in",
        "al",
        "se",
        "an",
        "en",
        "on",
        "cy",
        "dy",
        "fy",
        "gy",
        "hy",
        "ly",
        "my",
        "ny",
        "py",
        "ry",
        "sy",
        "ty",
        "vy",
        "oy",
        "ing",
        "ers",
        "ate",
        "ent",
        "ion",
        "est",
        "ous",
        "art",
        "and",
        "the",
        "all",
        "for",
        "out",
        "are",
        "ear",
        "eat",
        "ter",
        "ver",
        "per",
        "pro",
        "pre",
        "con",
        "can",
        "car",
        "old",
        "one",
        "ome",
        "has",
        "hat",
        "her",
        "ish",
        "ast",
        "psy",
        "oly",
        "sty",
        "str",
        "tch",
        "ght",
        "ash",
        "ack",
        "ick",
        "ock",
        "uck",
        "ill",
        "ell",
        "own",
        "our",
        "air",
        "ore",
        "ure",
        "ice",
        "ace",
        "ine",
        "ide",
        "ake",
        "ale",
        "ame",
        "aba",
        "bac",
        "ab",
        "ac",
        "es",
        "ach",
        "ht",
        "alt",
        "wa",
        "ivi",
        "vid",
        "vi",
        "iv",
        "id",
        "ult",
        "tra",
        "ul",
        "ra",
        "to",
        "ic",
        "ua",
        "at",
        "hin",
        "ino",
        "rh",
        "hi",
        "no",
        "ue",
        "eu",
        "pi",
        "oni",
        "nio",
        "ni",
        "io",
        "nin",
        "lla",
        "lam",
        "ama",
        "la",
        "am",
        "oal",
        "ala",
        "ko",
        "uic",
        "icy",
        "ui",
        "glo",
        "loo",
        "ig",
        "lo",
        "ena",
        "na",
        "ps",
        "ord",
        "rd",
        "bu",
        "om",
        "iom",
        "hak",
        "ha",
        "ak",
        "ki",
        "ba",
        "be",
        "bi",
        "bo",
        "by",
        "ca",
        "ce",
        "ci",
        "cu",
        "da",
        "de",
        "di",
        "do",
        "du",
        "fa",
        "fe",
        "fi",
        "fo",
        "fu",
        "ga",
        "ge",
        "gi",
        "go",
        "gu",
        "ka",
        "ke",
        "ku",
        "ky",
        "li",
        "lu",
        "me",
        "mi",
        "mo",
        "mu",
        "ne",
        "nu",
        "pe",
        "po",
        "pu",
        "ri",
        "ro",
        "ru",
        "sa",
        "si",
        "so",
        "su",
        "ta",
        "ti",
        "tu",
        "va",
        "ve",
        "vo",
        "we",
        "wi",
        "wo",
        "ad",
        "ed",
        "od",
        "ud",
        "af",
        "ef",
        "if",
        "of",
        "uf",
        "ag",
        "eg",
        "og",
        "ug",
        "ah",
        "ek",
        "ik",
        "ok",
        "em",
        "im",
        "um",
        "ap",
        "ep",
        "ip",
        "op",
        "up",
        "as",
        "is",
        "os",
        "us",
        "av",
        "ev",
        "ov",
        "uv",
        "aw",
        "ew",
        "ow",
        "ist",
        "ity",
        "ify",
        "ary",
        "ery",
        "ory",
        "ant",
        "ece",
        "eep",
        "eal",
        "eam",
        "ean",
        "eap",
        "eas",
        "ble",
        "cle",
        "dle",
        "fle",
        "gle",
        "ple",
        "sle",
        "ban",
        "bin",
        "bon",
        "bun",
        "cen",
        "cin",
        "dan",
        "den",
        "din",
        "don",
        "man",
        "men",
        "min",
        "mon",
        "pan",
        "pen",
        "pin",
        "pun",
        "ran",
        "ren",
        "rin",
        "ron",
        "run",
        "tan",
        "ten",
        "tin",
        "ton",
        "tun",
        "ven",
        "vin",
        "win",
        "ull",
        "oll",
        "ass",
        "ess",
        "iss",
        "oss",
        "uss",
        "app",
        "ipp",
        "upp",
        "arr",
        "err"
    ],
    "hard": [
        "ja",
        "je",
        "jo",
        "ju",
        "nj",
        "qu",
        "za",
        "ze",
        "zo",
        "az",
        "iz",
        "oz",
        "uz",
        "zz",
        "ax",
        "ex",
        "ix",
        "ox",
        "xa",
        "xe",
        "xi",
        "xt",
        "qua",
        "squ",
        "equ",
        "qui",
        "que",
        "xy",
        "aze",
        "ize",
        "axi",
        "oxi",
        "hym",
        "oya",
        "ayo",
        "aye",
        "yer",
        "ya",
        "tz",
        "tox",
        "sq",
        "izz",
        "yr",
        "jui",
        "ye",
        "yp",
        "jor",
        "xio",
        "yi",
        "yo",
        "aj",
        "yin",
        "zon"
    ]
}

export const BOSS_REGISTRY = {
  wordle500: {
    id: "wordle500",
    category: "special",
    wordCount: 1,
    maxTurns: 8,
  },
  "four-word": {
    id: "four-word",
    category: "multi",
    wordCount: 4,
    maxTurns: 10,
  },
  "shape-boss": {
    id: "shape-boss",
    category: "shape",
    wordCount: 1,
    maxTurns: 6,
  },
};

export const BOSS_TYPES = Object.values(BOSS_REGISTRY);

export const SOLUTION_WORD_COUNT = 2315;
export const HARD_SOLUTION_WORD_COUNT = 798;

export const SHAPE_KEYS = [
  "shape-t",
  "shape-u",
  "shape-x",
  "shape-diamond",
  "shape-hourglass",
  "shape-arrow",
  "shape-heart",
  "shape-finger",
  "shape-smile",
  "shape-alien",
  "shape-sword",
  "shape-tree",
  "shape-cup",
  "shape-snake",
  "shape-check",
  "shape-star",
  "shape-boat",
  "shape-robot",
  "shape-key",
  "shape-lightning",
  "shape-mushroom",
  "shape-crown",
  "shape-bell",
  "shape-flag",
  "shape-anchor",
  "shape-spider",
  "shape-ghost",
  "shape-moon",
  "shape-shield",
  "shape-spade",
  "shape-fish",
  "shape-tulip",
  "shape-butterfly",
  "shape-camera",
  "shape-bone",
  "shape-rocket",
  "shape-lock",
  "shape-cherry",
  "shape-umbrella",
  "shape-anvil",
  "shape-flask",
  "shape-axe",
  "shape-cactus",
  "shape-car",
  "shape-guitar",
];

export const SHAPES = {
  "shape-t": [
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "G", "x", "x"],
  ],
  "shape-u": [
    ["G", "x", "x", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["Y", "x", "G", "x", "Y"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "G", "x", "G", "G"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-x": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-diamond": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-hourglass": [
    ["G", "G", "G", "G", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["Y", "x", "x", "x", "Y"],
  ],
  "shape-arrow": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-heart": [
    ["x", "G", "x", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-finger": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-smile": [
    ["x", "G", "x", "G", "x"],
    ["x", "x", "x", "x", "x"],
    ["Y", "x", "x", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-alien": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["Y", "x", "Y", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-sword": [
    ["Y", "x", "G", "x", "Y"],
    ["x", "Y", "G", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-tree": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "Y", "Y", "Y", "x"],
  ],
  "shape-cup": [
    ["G", "x", "G", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-snake": [
    ["G", "G", "x", "x", "x"],
    ["x", "G", "G", "x", "x"],
    ["x", "x", "G", "G", "x"],
    ["x", "x", "x", "Y", "Y"],
    ["x", "x", "Y", "Y", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-check": [
    ["x", "x", "x", "x", "G"],
    ["x", "x", "x", "G", "x"],
    ["G", "x", "G", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "Y", "x", "x", "x"],
    ["G", "G", "G", "G", "G"],
  ],
  "shape-star": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
    ["Y", "x", "x", "x", "Y"],
  ],
  "shape-boat": [
    ["x", "x", "x", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-robot": [
    ["x", "G", "G", "G", "x"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "G", "x", "G"],
    ["Y", "G", "x", "G", "Y"],
    ["x", "Y", "G", "Y", "x"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-key": [
    ["x", "G", "G", "G", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "Y", "x"],
  ],
  "shape-lightning": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "x", "x"],
    ["G", "Y", "G", "x", "x"],
    ["x", "x", "Y", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-mushroom": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-crown": [
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["Y", "x", "G", "x", "Y"],
    ["x", "Y", "x", "Y", "x"],
    ["G", "x", "x", "x", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-bell": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-flag": [
    ["x", "G", "G", "G", "x"],
    ["x", "G", "x", "Y", "x"],
    ["x", "G", "G", "G", "x"],
    ["x", "Y", "x", "x", "x"],
    ["x", "Y", "x", "x", "x"],
    ["x", "G", "x", "x", "x"],
  ],
  "shape-anchor": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-spider": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "Y", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "x", "x", "G"],
  ],
  "shape-ghost": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "x", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-moon": [
    ["x", "x", "G", "G", "x"],
    ["x", "G", "Y", "x", "x"],
    ["G", "x", "x", "x", "x"],
    ["G", "x", "Y", "x", "x"],
    ["x", "G", "x", "x", "x"],
    ["x", "x", "G", "G", "x"],
  ],
  "shape-shield": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "Y", "G", "Y", "x"],
    ["x", "x", "G", "x", "x"],
  ],
  "shape-spade": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-fish": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "Y"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-tulip": [
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-butterfly": [
    ["G", "x", "x", "x", "G"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-camera": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "x", "x", "x"],
  ],
  "shape-bone": [
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "G", "G", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
  ],
  "shape-rocket": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-lock": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["G", "x", "G", "x", "G"],
    ["G", "x", "Y", "x", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-cherry": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["x", "G", "x", "Y", "x"],
    ["G", "x", "x", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "x", "G", "x"],
  ],
  "shape-umbrella": [
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "x", "G", "x", "G"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "x", "x"],
  ],
  "shape-anvil": [
    ["x", "G", "G", "G", "x"],
    ["G", "x", "x", "Y", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "Y", "G", "x"],
    ["G", "Y", "x", "Y", "G"],
  ],
  "shape-flask": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "G", "x", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "Y", "x", "Y", "G"],
    ["x", "G", "G", "G", "x"],
  ],
  "shape-axe": [
    ["x", "G", "G", "x", "x"],
    ["G", "Y", "G", "x", "x"],
    ["x", "G", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "x", "Y", "x", "x"],
  ],
  "shape-cactus": [
    ["x", "x", "G", "x", "x"],
    ["x", "x", "G", "x", "G"],
    ["G", "x", "G", "Y", "G"],
    ["G", "Y", "G", "x", "x"],
    ["x", "x", "G", "x", "x"],
    ["x", "Y", "G", "Y", "x"],
  ],
  "shape-car": [
    ["x", "x", "x", "x", "x"],
    ["x", "G", "G", "G", "x"],
    ["G", "x", "Y", "x", "G"],
    ["G", "G", "G", "G", "G"],
    ["x", "G", "x", "G", "x"],
    ["x", "Y", "x", "Y", "x"],
  ],
  "shape-guitar": [
    ["G", "x", "x", "x", "G"],
    ["x", "Y", "Y", "Y", "x"],
    ["G", "x", "G", "x", "G"],
    ["G", "G", "G", "G", "G"],
    ["x", "x", "Y", "x", "x"],
    ["G", "x", "x", "x", "G"],
  ],
};
